// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_HF_produtos.Models;

#nullable disable

namespace api_HF_produtos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251004180520_m01")]
    partial class m01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api_HF_produtos.Models.Cliente", b =>
                {
                    b.Property<int>("Id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_cliente"));

                    b.Property<int>("CPF")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Hospedagem", b =>
                {
                    b.Property<int>("Id_hospedagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_hospedagem"));

                    b.Property<int>("ClienteId_cliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_in")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_out")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuartoId_quarto")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor_hospedagem")
                        .HasColumnType("Decimal(18,2)");

                    b.HasKey("Id_hospedagem");

                    b.HasIndex("ClienteId_cliente");

                    b.HasIndex("QuartoId_quarto");

                    b.ToTable("Hospedagens");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Pedido", b =>
                {
                    b.Property<int>("Id_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_pedido"));

                    b.Property<int?>("ClienteId_cliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("HospedagemId_hospedagem")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoId_pedido")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_pedido");

                    b.HasIndex("ClienteId_cliente");

                    b.HasIndex("HospedagemId_hospedagem");

                    b.HasIndex("PedidoId_pedido");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Pedido_item", b =>
                {
                    b.Property<int>("Id_pedido_item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_pedido_item"));

                    b.Property<int>("Id_pedido")
                        .HasColumnType("int");

                    b.Property<int>("Id_produto")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoId_pedido")
                        .HasColumnType("int");

                    b.Property<decimal>("Preço")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<int?>("ProdutoId_produto")
                        .HasColumnType("int");

                    b.Property<int>("quantidade_item")
                        .HasColumnType("int");

                    b.HasKey("Id_pedido_item");

                    b.HasIndex("PedidoId_pedido");

                    b.HasIndex("ProdutoId_produto");

                    b.ToTable("Pedido_itens");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Produto", b =>
                {
                    b.Property<int>("Id_produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_produto"));

                    b.Property<string>("Nome_produto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preço")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<string>("Tipo_produto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id_produto");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Quarto", b =>
                {
                    b.Property<int>("Id_quarto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_quarto"));

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_quarto")
                        .HasColumnType("int");

                    b.HasKey("Id_quarto");

                    b.ToTable("Quartos");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Hospedagem", b =>
                {
                    b.HasOne("api_HF_produtos.Models.Cliente", "Cliente")
                        .WithMany("Hospedagens")
                        .HasForeignKey("ClienteId_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_HF_produtos.Models.Quarto", "Quarto")
                        .WithMany("hospedagems")
                        .HasForeignKey("QuartoId_quarto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Quarto");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Pedido", b =>
                {
                    b.HasOne("api_HF_produtos.Models.Cliente", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId_cliente");

                    b.HasOne("api_HF_produtos.Models.Hospedagem", "Hospedagem")
                        .WithMany("Pedidos")
                        .HasForeignKey("HospedagemId_hospedagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_HF_produtos.Models.Pedido", null)
                        .WithMany("Pedidos_item")
                        .HasForeignKey("PedidoId_pedido");

                    b.Navigation("Hospedagem");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Pedido_item", b =>
                {
                    b.HasOne("api_HF_produtos.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId_pedido");

                    b.HasOne("api_HF_produtos.Models.Produto", "Produto")
                        .WithMany("Pedidos_item")
                        .HasForeignKey("ProdutoId_produto");

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Cliente", b =>
                {
                    b.Navigation("Hospedagens");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Hospedagem", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Pedido", b =>
                {
                    b.Navigation("Pedidos_item");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Produto", b =>
                {
                    b.Navigation("Pedidos_item");
                });

            modelBuilder.Entity("api_HF_produtos.Models.Quarto", b =>
                {
                    b.Navigation("hospedagems");
                });
#pragma warning restore 612, 618
        }
    }
}
